### ISSUE TITLE
materials

### ISSUE THREAD

**Issue by ekswathi** [TLabAltoh/realistic_terrain#1]
Really nice bro. working perfect with A.N.T landscape addon.
any possibilities for making shaders for terrain?

**Comment by TLabAltoh** [comment]
Thanks for the comment. I am hoping to add shaders in the next update, although I am not sure when that will be.

**Comment by TLabAltoh** [comment]
I have added terrain materials to the add-ons in the update. I will add it as a shader after some more improvements.

**Comment by ekswathi** [comment]
i tried the new update. but show the error module material has no attribute "terrainmaterial"

**Comment by TLabAltoh** [comment]
Thank you for the information. When did the error occur? If possible, disable realistic terrain once, then quit Blender and try
``` C:\Users\{USER_NAME}\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\realistic-terrain ```
with the new version of the file, then restart Blender, enable realistic terrain and see if it works.

**Comment by TLabAltoh** [comment]
# v1.2 Release
The module import method has been changed. Uninstall realistic-terrain (version 1.1 or earlier) already installed, and then install version 1.2 or later to Blender to see if it works properly.

**Comment by ekswathi** [comment]
really nice. now working perfect.
thank you for the quick response.
